worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  # Timeout settings
  send_timeout 60s;
  client_body_timeout 60s;
  client_header_timeout 60s;
  keepalive_timeout 65s;

  server {
    listen 3128;

    access_log /dev/stdout;
    error_log  /dev/stderr;

    map $request_port $allow_port {
        443            1;
        563            1;
    }

    # map $host $allow_host {
    #     hostnames;

    #     example.org    1;
    #     *.example.org  1;
    # }

    resolver 1.1.1.1 ipv6=off valid=5s;

    if ($allow_port != 1) {
        return 502;
    }

    # if ($allow_host != 1) {
    #     return 502;
    # }

    tunnel_pass;
  }
}
